export type GalleryCategory =
  | "community"
  | "healthcare"
  | "education"
  | "international"
  | "sports"
  | "disability"
  | "certificates"
  | "leadership"

export type GalleryItem = {
  src: string // public/ path, e.g., /images/community/helping-elderly-01.jpg
  alt: string
  category: GalleryCategory
  title?: string
  caption?: string
  date?: string // YYYY-MM or YYYY
  tags?: string[]
}

export const gallery: GalleryItem[] = [
  // Community Service
  {
    src: "/images/community/MG-52216-5.jpg",
    alt: "Community service volunteers helping local residents",
    category: "community",
    title: "Community Outreach",
    caption: "Serving the local community",
    tags: ["service", "community"],
  },
  {
    src: "/images/community/MG-52225-1.jpg",
    alt: "Community engagement program",
    category: "community",
    title: "Community Service",
    caption: "Active community participation",
    tags: ["service", "community"],
  },
  {
    src: "/images/community/MG-52225-3.jpg",
    alt: "Community welfare initiative",
    category: "community",
    title: "Welfare Programs",
    caption: "Supporting community needs",
    tags: ["welfare", "community"],
  },
  {
    src: "/images/community/MG-52225-4.jpg",
    alt: "Community development project",
    category: "community",
    title: "Community Development",
    caption: "Building stronger communities",
    tags: ["development", "community"],
  },
  {
    src: "/images/community/MG-52225-5.jpg",
    alt: "Social service activities",
    category: "community",
    title: "Social Service",
    caption: "Dedicated to serving society",
    tags: ["service", "social"],
  },
  // Healthcare
  {
    src: "/images/healthcare/DSC_1135.JPG",
    alt: "Healthcare initiative",
    category: "healthcare",
    title: "Health Services",
    caption: "Providing quality healthcare",
    tags: ["health", "medical"],
  },
  {
    src: "/images/healthcare/DSC_1137.JPG",
    alt: "Medical facility visit",
    category: "healthcare",
    title: "Medical Support",
    caption: "Supporting medical infrastructure",
    tags: ["medical", "healthcare"],
  },
  {
    src: "/images/healthcare/DSC_1139.JPG",
    alt: "Health camp organization",
    category: "healthcare",
    title: "Health Camp",
    caption: "Free medical checkups for community",
    tags: ["medical", "healthcare"],
  },
  {
    src: "/images/healthcare/DSC_1142.JPG",
    alt: "Blood bank support",
    category: "healthcare",
    title: "Blood Bank",
    caption: "Life-saving blood donation initiative",
    tags: ["blood-bank", "healthcare"],
  },
  {
    src: "/images/healthcare/DSC_1146.JPG",
    alt: "Medical services",
    category: "healthcare",
    title: "Medical Services",
    caption: "Comprehensive healthcare support",
    tags: ["medical", "healthcare"],
  },
  {
    src: "/images/healthcare/DSC_1148.JPG",
    alt: "Healthcare program",
    category: "healthcare",
    title: "Healthcare Initiative",
    caption: "Community health programs",
    tags: ["health", "community"],
  },
  {
    src: "/images/healthcare/DSC_1150.JPG",
    alt: "Medical assistance",
    category: "healthcare",
    title: "Medical Aid",
    caption: "Providing medical assistance",
    tags: ["medical", "aid"],
  },
  {
    src: "/images/healthcare/DSC_1151.JPG",
    alt: "Health facility",
    category: "healthcare",
    title: "Health Facility",
    caption: "Modern health infrastructure",
    tags: ["health", "facility"],
  },
  {
    src: "/images/healthcare/DSC_1152.JPG",
    alt: "Medical support program",
    category: "healthcare",
    title: "Medical Program",
    caption: "Ongoing medical support",
    tags: ["medical", "program"],
  },
  {
    src: "/images/healthcare/DSC_1155.JPG",
    alt: "Healthcare services",
    category: "healthcare",
    title: "Health Services",
    caption: "Quality healthcare delivery",
    tags: ["healthcare", "services"],
  },
  {
    src: "/images/healthcare/DSC_1156.JPG",
    alt: "Medical initiative",
    category: "healthcare",
    title: "Medical Initiative",
    caption: "Community medical programs",
    tags: ["medical", "community"],
  },
  {
    src: "/images/healthcare/DSC_1160.JPG",
    alt: "Health support",
    category: "healthcare",
    title: "Health Support",
    caption: "Supporting community health",
    tags: ["health", "support"],
  },
  {
    src: "/images/healthcare/Photo 19a.JPG",
    alt: "Medical facility",
    category: "healthcare",
    title: "Medical Facility",
    caption: "State-of-the-art medical infrastructure",
    tags: ["medical", "facility"],
  },
  // Education / Universities
  {
    src: "/images/education/DSC_0225.JPG",
    alt: "Educational facility",
    category: "education",
    title: "Educational Infrastructure",
    caption: "Building future through education",
    tags: ["education", "infrastructure"],
  },
  {
    src: "/images/education/DSC_0231.JPG",
    alt: "Educational program",
    category: "education",
    title: "Education Support",
    caption: "Promoting quality education",
    tags: ["education", "support"],
  },
  {
    src: "/images/education/DSC_0235.JPG",
    alt: "School infrastructure",
    category: "education",
    title: "School Development",
    caption: "Developing educational facilities",
    tags: ["school", "development"],
  },
  {
    src: "/images/education/Photo 1a.jpg",
    alt: "Educational initiative",
    category: "education",
    title: "Education Initiative",
    caption: "Empowering through education",
    tags: ["education", "empowerment"],
  },
  {
    src: "/images/education/Photo 1.jpg",
    alt: "Educational support program",
    category: "education",
    title: "Education Program",
    caption: "Supporting educational excellence",
    tags: ["education", "program"],
  },
  {
    src: "/images/education/Photo 3.jpg",
    alt: "School support",
    category: "education",
    title: "School Support",
    caption: "Providing educational resources",
    tags: ["education", "school"],
  },
  {
    src: "/images/education/Shelters 004.jpg",
    alt: "Educational shelter",
    category: "education",
    title: "Education Shelter",
    caption: "Safe learning environment",
    tags: ["education", "shelter"],
  },
  {
    src: "/images/education/Shelters 006.jpg",
    alt: "Learning facility",
    category: "education",
    title: "Learning Facility",
    caption: "Modern learning infrastructure",
    tags: ["education", "facility"],
  },
  // International Visitors
  {
    src: "/images/international/Rot1.jpg",
    alt: "International Rotarians visit",
    category: "international",
    title: "Global Fellowship",
    caption: "International Rotary collaboration",
    tags: ["international", "rotary"],
  },
  {
    src: "/images/international/Rot2.jpg",
    alt: "International exchange program",
    category: "international",
    title: "International Exchange",
    caption: "Cultural exchange program",
    tags: ["exchange", "international"],
  },
  {
    src: "/images/international/Rot3.jpg",
    alt: "Foreign Rotarians at Sangli",
    category: "international",
    title: "Global Partners",
    caption: "Visiting Rotarians from abroad",
    tags: ["international", "partnership"],
  },
  {
    src: "/images/international/Rot5.jpg",
    alt: "International collaboration",
    category: "international",
    title: "International Collaboration",
    caption: "Working together globally",
    tags: ["international", "collaboration"],
  },
  {
    src: "/images/international/Rot7.jpg",
    alt: "Global Rotary network",
    category: "international",
    title: "Rotary Network",
    caption: "Part of global Rotary family",
    tags: ["rotary", "network"],
  },
  {
    src: "/images/international/Rot8.jpg",
    alt: "International visitors",
    category: "international",
    title: "International Guests",
    caption: "Welcoming global Rotarians",
    tags: ["international", "guests"],
  },
  {
    src: "/images/international/Rot9.jpg",
    alt: "Cross-border partnership",
    category: "international",
    title: "Global Partnership",
    caption: "International Rotary cooperation",
    tags: ["international", "partnership"],
  },
  {
    src: "/images/international/Rot11.jpg",
    alt: "International fellowship",
    category: "international",
    title: "International Fellowship",
    caption: "Building global connections",
    tags: ["fellowship", "international"],
  },
  {
    src: "/images/international/Rot13.jpg",
    alt: "Global Rotary collaboration",
    category: "international",
    title: "Global Collaboration",
    caption: "Rotary International partnership",
    tags: ["rotary", "global"],
  },
  // Sports / Wellness
  {
    src: "/images/sports/Photo 8a.JPG",
    alt: "Swimming pool facility",
    category: "sports",
    title: "Swimming Pool",
    caption: "Rambhau Bhide Swimming Pool",
    tags: ["swimming", "sports"],
  },
  {
    src: "/images/sports/Photo 8b.JPG",
    alt: "Sports wellness facility",
    category: "sports",
    title: "Sports Facility",
    caption: "Community wellness initiative",
    tags: ["sports", "wellness"],
  },
  {
    src: "/images/sports/Photo 8c.jpg",
    alt: "Fitness center",
    category: "sports",
    title: "Fitness Center",
    caption: "Health and wellness facility",
    tags: ["fitness", "wellness"],
  },
  {
    src: "/images/sports/Photo 9a.JPG",
    alt: "Sports infrastructure",
    category: "sports",
    title: "Sports Infrastructure",
    caption: "Promoting physical fitness",
    tags: ["sports", "fitness"],
  },
  {
    src: "/images/sports/Photo 9b.JPG",
    alt: "Wellness program",
    category: "sports",
    title: "Wellness Program",
    caption: "Community health and fitness",
    tags: ["wellness", "health"],
  },
  // Disability Support
  {
    src: "/images/disability/05.JPG",
    alt: "Disability support program",
    category: "disability",
    title: "Rehabilitation Support",
    caption: "Assistive devices distribution",
    tags: ["disability", "support"],
  },
  {
    src: "/images/disability/13.JPG",
    alt: "Prosthetic limb support",
    category: "disability",
    title: "Prosthetic Support",
    caption: "Providing mobility assistance",
    tags: ["prosthetic", "disability"],
  },
  {
    src: "/images/disability/21.JPG",
    alt: "Rehabilitation center",
    category: "disability",
    title: "Rehabilitation Center",
    caption: "Comprehensive care for persons with disabilities",
    tags: ["rehabilitation", "disability"],
  },
  {
    src: "/images/disability/32.JPG",
    alt: "Disability assistance",
    category: "disability",
    title: "Disability Assistance",
    caption: "Supporting specially-abled individuals",
    tags: ["disability", "assistance"],
  },
  {
    src: "/images/disability/35.JPG",
    alt: "Rehabilitation program",
    category: "disability",
    title: "Rehabilitation Program",
    caption: "Enabling independent living",
    tags: ["rehabilitation", "program"],
  },
  {
    src: "/images/disability/DSC_0005.JPG",
    alt: "Disability support initiative",
    category: "disability",
    title: "Support Initiative",
    caption: "Empowering persons with disabilities",
    tags: ["disability", "empowerment"],
  },
  {
    src: "/images/disability/Photo 15a.jpg",
    alt: "Prosthetic camp",
    category: "disability",
    title: "Prosthetic Camp",
    caption: "Free prosthetic limb distribution",
    tags: ["prosthetic", "camp"],
  },
  {
    src: "/images/disability/Photo 15b.jpg",
    alt: "Mobility support",
    category: "disability",
    title: "Mobility Support",
    caption: "Wheelchair and assistive devices",
    tags: ["mobility", "support"],
  },
  {
    src: "/images/disability/Photo 15c.jpg",
    alt: "Rehabilitation services",
    category: "disability",
    title: "Rehabilitation Services",
    caption: "Comprehensive rehabilitation care",
    tags: ["rehabilitation", "services"],
  },
  {
    src: "/images/disability/Photo 15d.jpg",
    alt: "Disability care",
    category: "disability",
    title: "Disability Care",
    caption: "Dedicated care for specially-abled",
    tags: ["disability", "care"],
  },
  {
    src: "/images/disability/Photo 15e.jpg",
    alt: "Assistive device distribution",
    category: "disability",
    title: "Assistive Devices",
    caption: "Providing mobility aids",
    tags: ["assistive", "devices"],
  },
  {
    src: "/images/disability/Photo 15f.jpg",
    alt: "Rehabilitation support",
    category: "disability",
    title: "Rehabilitation Support",
    caption: "Supporting independent living",
    tags: ["rehabilitation", "independence"],
  },
  {
    src: "/images/disability/Photo 15.JPG",
    alt: "Disability rehabilitation",
    category: "disability",
    title: "Disability Rehabilitation",
    caption: "Comprehensive rehabilitation program",
    tags: ["disability", "rehabilitation"],
  },
  // Certificates
  {
    src: "/images/certificates/DSC_1144.JPG",
    alt: "Trust certificate",
    category: "certificates",
    title: "Trust Certificate",
    caption: "Official trust documentation",
    tags: ["certificate", "trust"],
  },
  {
    src: "/images/certificates/Photo 19bb.JPG",
    alt: "Registration certificate",
    category: "certificates",
    title: "Registration Certificate",
    caption: "Official registration document",
    tags: ["certificate", "registration"],
  },
  {
    src: "/images/certificates/Rotary Sangli Charter Certificate 1948.jpg",
    alt: "Rotary Sangli Charter Certificate 1948",
    category: "certificates",
    title: "Charter Certificate 1948",
    caption: "Original Rotary Club Sangli Charter",
    date: "1948",
    tags: ["charter", "certificate"],
  },
  // Leadership / Presidents
  {
    src: "/images/leadership/Abhayankar Shrikrishna.jpg",
    alt: "Rtn. Abhayankar Shrikrishna",
    category: "leadership",
    title: "Rtn. Abhayankar Shrikrishna",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
  {
    src: "/images/leadership/Arwade Sanatkumar1.jpg",
    alt: "Rtn. Arwade Sanatkumar",
    category: "leadership",
    title: "Rtn. Arwade Sanatkumar",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
  {
    src: "/images/leadership/Chafalkar Appasaheb.jpg",
    alt: "Rtn. Chafalkar Appasaheb",
    category: "leadership",
    title: "Rtn. Chafalkar Appasaheb",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
  {
    src: "/images/leadership/Chafalkar Bapusaheb.jpg",
    alt: "Rtn. Chafalkar Bapusaheb",
    category: "leadership",
    title: "Rtn. Chafalkar Bapusaheb",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
  {
    src: "/images/leadership/Chidgupkar Dr.jpg",
    alt: "Rtn. Dr. Chidgupkar",
    category: "leadership",
    title: "Rtn. Dr. Chidgupkar",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
  {
    src: "/images/leadership/Chitale Ramkrishna1.jpg",
    alt: "Rtn. Chitale Ramkrishna",
    category: "leadership",
    title: "Rtn. Chitale Ramkrishna",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
  {
    src: "/images/leadership/Chopade S. G.jpg",
    alt: "Rtn. Chopade S. G.",
    category: "leadership",
    title: "Rtn. Chopade S. G.",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
  {
    src: "/images/leadership/Chougale Keshavrao A.jpg",
    alt: "Rtn. Chougale Keshavrao A.",
    category: "leadership",
    title: "Rtn. Chougale Keshavrao A.",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
  {
    src: "/images/leadership/Daftardar.jpg",
    alt: "Rtn. Daftardar",
    category: "leadership",
    title: "Rtn. Daftardar",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
  {
    src: "/images/leadership/Dandekar Arun.jpg",
    alt: "Rtn. Dandekar Arun",
    category: "leadership",
    title: "Rtn. Dandekar Arun",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
  {
    src: "/images/leadership/Magdum Dr. Kishore.jpg",
    alt: "Rtn. Dr. Kishore Magdum",
    category: "leadership",
    title: "Rtn. Dr. Kishore Magdum",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
  {
    src: "/images/leadership/Shevade Bipin.jpg",
    alt: "Rtn. Bipin Shevade",
    category: "leadership",
    title: "Rtn. Bipin Shevade",
    caption: "Past President",
    tags: ["president", "leadership"],
  },
]
